### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by ithakaa** [QianheYu/headscale-panel-ui#1]
error

https://pastebin.com/sAqYmyfJ

**Comment by QianheYu** [comment]
You need to run `export NODE_OPTIONS=--openssl-legacy-provider` before running the `npm run build:prod` command. 
[For more information see stackoverflow](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)

**Comment by ithakaa** [comment]
> You need to run `export NODE_OPTIONS=--openssl-legacy-provider` before running the `npm run build:prod` command. 
> 
> [For more information see stackoverflow](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)

Do you have a full installation guide? 

That step was not listed in the installation instructions
