### ISSUE TITLE
配置文件显示不全

### ISSUE THREAD

**Issue by VMCoud** [QianheYu/headscale-panel-ui#3]
![image](https://github.com/QianheYu/headscale-panel-ui/assets/59264435/8e1c806f-40d1-4923-b138-362613bbed1c)
后端返回数据是完整的

**Comment by QianheYu** [comment]
> ![image](https://user-images.githubusercontent.com/59264435/265024148-8e1c806f-40d1-4923-b138-362613bbed1c.png) 后端返回数据是完整的
这是前端的问题，暂时的情况是，你向下滚动一下然后点击未显示出来的部分就正常了。至于为什么会这样我暂时也不了解，我目前对前端了解不多。

**Comment by QianheYu** [comment]
> ![image](https://user-images.githubusercontent.com/59264435/265024678-2cddf058-1cce-44bb-9f91-9d54bde8d701.png)

目前该项目在element-vue-admin的基础上开发而来，该问题是由于element-vue-admin并没有适配移动端。
如果您会开发前端，欢迎您为移动端适配。

**Comment by VMCoud** [comment]
> > ![image](https://user-images.githubusercontent.com/59264435/265024678-2cddf058-1cce-44bb-9f91-9d54bde8d701.png)
> 
> 目前该项目在element-vue-admin的基础上开发而来，该问题是由于element-vue-admin并没有适配移动端。 如果您会开发前端，欢迎您为移动端适配。

![image](https://github.com/QianheYu/headscale-panel-ui/assets/59264435/058c71f1-aac9-4bbf-bbee-6e5581176327)
![image](https://github.com/QianheYu/headscale-panel-ui/assets/59264435/6e5be7e2-1d1e-48bf-b641-3bce2e667e4c)
宽度改为90手机端可正常显示

**Comment by VMCoud** [comment]
![image](https://github.com/QianheYu/headscale-panel-ui/assets/59264435/626c2605-d63a-4ce3-8bcb-8dc91d69bf48)

**Comment by VMCoud** [comment]
感谢开发这么好的项目

**Comment by QianheYu** [comment]
> ![image](https://user-images.githubusercontent.com/59264435/265058187-626c2605-d63a-4ce3-8bcb-8dc91d69bf48.png)

前端更新到v0.1.4版本后dialog可以自适应了
