### ISSUE TITLE
求部署教程

### ISSUE THREAD

**Issue by Celdrick** [QianheYu/headscale-panel-ui#6]
前后端均已编译成功，但是部署了无法登陆，看了日志也没有反馈
npm run dev模式下访问前端返回Invalid Host header。
后端api也没有访问记录，但是后端可以单独访问，是成功的。

**Comment by QianheYu** [comment]
请您先检查是否在构建前修改了项目根目录下.env.production文件中地址为后端的地址，或在dev模式修改.env.development文件中后端的地址。

**Comment by Celdrick** [comment]
> 请您先检查是否在构建前修改了项目根目录下.env.production文件中地址为后端的地址，或在dev模式修改.env.development文件中后端的地址。

感谢大佬，用的nginx反向代理，也要修改为域名。但是现在后端报错：
headscale-panel/middleware.unauthorized JWT authentication failed, error code: 401, error message: Cannot decrypt, private key may be incorrect, crypto/rsa: decryption error

应该是我用的你的文档https://github.com/QianheYu/headscale-panel/blob/main/docs/self%20signed%20certificates.md生成的两个RSA私钥公钥文件错误，请问具体生成是用这个文档吗？生成的格式和你给的样例不一致。
[headscale-panel-priv.pem][headscale-panel-pub.pem]

**Comment by QianheYu** [comment]
由于在登陆时使用 密钥对 对密码使用了加密传输，前端进行了加密，后端进行解密解密。你需要检查前端页面中的publickey和后端配置文件所指定的密钥是否对应。如果你使用的密钥对是自己生成的，你需要在前端页面`views/login/index.vue` `views/system/user/index.vue` `views/profile/components/Account.vue`代码中进行替换，否则请在后端配置文件中设置项目中的密钥对。
如仍有问题请反馈。（提示：因为headscale的0.23.x版接口更新，暂时仅main分支支持，但仍在修复历史bug与适配进程中，可能存在bug）

**Comment by Celdrick** [comment]
> 由于在登陆时使用 密钥对 对密码使用了加密传输，前端进行了加密，后端进行解密解密。你需要检查前端页面中的publickey和后端配置文件所指定的密钥是否对应。如果你使用的密钥对是自己生成的，你需要在前端页面`views/login/index.vue` `views/system/user/index.vue` `views/profile/components/Account.vue`代码中进行替换，否则请在后端配置文件中设置项目中的密钥对。(配置文件的system中的rsa-public-key和rsa-private-key) 如仍有问题请反馈。（提示：因为headscale的0.23.x版接口更新，暂时仅main分支支持，但仍在修复历史bug与适配进程中，可能存在bug）

搞定了，感谢大佬
