### ISSUE TITLE
访问System下的功能时页面容易卡死

### ISSUE THREAD

**Issue by arounyf** [QianheYu/headscale-panel-ui#8]
1、访问System中的功能时页面时不时会卡死，貌似触发了死循环

<img width="1109" alt="屏幕截图 2024-07-02 103450" src="https://github.com/QianheYu/headscale-panel/assets/62204996/e2cda5f2-c023-4296-965e-77a3144c4d16">
<img width="1280" alt="屏幕截图 2024-07-03 132759" src="https://github.com/QianheYu/headscale-panel/assets/62204996/b3947e45-7114-4e7a-89d6-d45f00b98dac">

说明 本人使用的docker部署，采用standalone模式部署，前后端在同一台机器上

经过我自己的排查发现将这段代码注释之后就没问题了
```JavaScript
/*             F() && (s["default"].config.errorHandler = function(e, t, n, a) {
                s["default"].nextTick((function() {
                    v["a"].dispatch("errorLog/addErrorLog", {
                        err: e,
                        vm: t,
                        info: n,
                        url: window.location.href
                    }), console.error(e, n)

                }))
            }); */
```
但是我并不具备理解这段代码的能力，希望得到优化，这里我非常感谢作者的这个项目，我觉得该项目做的非常棒

**Comment by QianheYu** [comment]
感谢您提供的bug线索，新版本正在重构中，将在未来的版本中得到修复

**Comment by arounyf** [comment]
很高兴能得到你的回复，此项目我很喜欢，但是我也有一些我自己的建议，比如说实现多用户之间隔离，支持sqlite数据库

**Comment by QianheYu** [comment]
用户隔离功能在测试版中已经实现，但方法并不合适。将在重构的版本中优化，同时也会试图支持sqlite。
如果目前确实需要用户隔离可以暂时使用测试版，docker拉取headscale-panel:test镜像进行部署。
